services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sat-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - sat-network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: sat-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sat-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: sat-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sat_challenge
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - sat-db-data:/var/lib/mysql
    networks:
      - sat-network

networks:
  sat-network:
    driver: bridge

volumes:
  sat-db-data:
    driver: local
